sudo: required
services:
  - docker 
before_install:
  - docker build -t sanchit .

script:
  - docker run -e CI=true sanchit npm run test


deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "access"
  secret_access_key:
    secure: "sc"
  region: "us-east-1"  
  app: "SanchitChawla"
  env: "Sanchitchawla-env"
  bucket_name: "elasticbeanstalk-us-east-1-017544707512"
