sudo: required
services:
  - docker 
before_install:
  - docker build -t sanchit .

script:
  - docker run -e CI=true sanchit npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"  
  app: "SanchitChawla"
  env: "Sanchitchawla-env"
  bucket_name: "elasticbeanstalk-us-east-1-017544707512"
  on:
    branch: master
  access_key_id: 
  secure: "$AWS_ACCESS_KEY"
  secret_access_key:
  secure: "$AWS_SECRET_KEY"
